/**
 * @file app_main.c
 * @author
 * @brief Application code built on the Nucleo-F411RE board and STM32Cube
 * autogenerated code.
 * @date 2024-06-27
 *
 * @copyright Copyright (c) 2024
 *
 */

#include <assert.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "driver_esp8266.h"
#include "main.h"
#include "peripheral_init.h"
#include "stm32f4xx_hal_uart.h"

extern void SystemClock_Config(void); // grabs auto-generated function from main.c
static UART_HandleTypeDef *printf_uart = NULL;
static UART_HandleTypeDef *uart1 = NULL;

int __io_putchar(int ch) {
  uint8_t c = ch;
  if (printf_uart) {
    HAL_UART_Transmit(printf_uart, &c, 1, HAL_MAX_DELAY);
  }
  return ch;
}

int __io_getchar(void) {
  uint8_t c;
  if (printf_uart) {
    HAL_UART_Receive(printf_uart, &c, 1, HAL_MAX_DELAY);
  }
  return c;
}

int main(void) {
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  UART_HandleTypeDef *uart1 = MX_USART1_UART_Init();
  UART_HandleTypeDef *uart2 = MX_USART2_UART_Init();
  printf_uart = uart2;

  printf("\n\r(%s:%d) START PROGRAM\n\r", __FILE__, __LINE__);

  uint8_t resp[128] = {0};
  AT_Command_Print(uart1, "AT", resp, sizeof(resp));
  assert(NULL != AT_Command_Print(uart1, "AT+CWMODE_CUR=1", resp, sizeof(resp)));
  assert(NULL != AT_Command_Print(uart1, "AT+CWJAP_CUR=\"tiglath\",\"thedog123\"", resp, sizeof(resp)));
  assert(NULL != AT_Command_Print(uart1, "AT+CIFSR", resp, sizeof(resp)));

  while (1) {
    HAL_Delay(1000);
  }
}
